/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "primary-container": "#3d4757",
        "inverse-primary": "#556071",
        "inverse-surface": "#f9f9ff",
        "on-error-container": "#ff9993",
        "on-primary": "#374151",
        "secondary-fixed-dim": "#cbd5e8",
        "outline": "#5f75a5",
        "on-surface-variant": "#95abde",
        "on-primary-fixed": "#364050",
        "on-surface": "#dde5ff",
        "error": "#ee7d77",
        "surface": "#070e1d",
        "on-error": "#490106",
        "surface-container-lowest": "#000000",
        "surface-container-highest": "#082450",
        "on-tertiary-fixed": "#2e3949",
        "surface-bright": "#062a5f",
        "primary": "#bdc7db",
        "secondary-dim": "#949eb0",
        "tertiary": "#dbe6fb",
        "surface-container-high": "#091f42",
        "tertiary-container": "#cdd8ed",
        "secondary-fixed": "#d9e3f6",
        "tertiary-fixed": "#cdd8ed",
        "secondary-container": "#323c4b",
        "on-background": "#dde5ff",
        "on-secondary": "#17212e",
        "inverse-on-surface": "#4e5566",
        "on-tertiary-container": "#414b5c",
        "on-secondary-fixed": "#36404f",
        "primary-fixed": "#d9e3f7",
        "on-primary-fixed-variant": "#525c6d",
        "secondary": "#949eb0",
        "surface-dim": "#070e1d",
        "on-primary-container": "#c7d1e5",
        "primary-dim": "#afb9cd",
        "background": "#070e1d",
        "surface-container-low": "#081328",
        "on-tertiary-fixed-variant": "#4a5566",
        "on-secondary-fixed-variant": "#525c6c",
        "error-dim": "#bb5551",
        "surface-variant": "#082450",
        "surface-tint": "#bdc7db",
        "tertiary-fixed-dim": "#bfcade",
        "error-container": "#7f2927",
        "primary-fixed-dim": "#cbd5e9",
        "on-secondary-container": "#b6c0d2",
        "tertiary-dim": "#bfcade",
        "on-tertiary": "#495465",
        "surface-container": "#091935",
        "outline-variant": "#314774"
      },
      fontFamily: {
        "headline": ["Be Vietnam Pro", "sans-serif"],
        "body": ["Inter", "sans-serif"],
        "label": ["Inter", "sans-serif"]
      },
      borderRadius: {"DEFAULT": "0.125rem", "lg": "0.25rem", "xl": "0.5rem", "full": "0.75rem"},
    },
  },
  plugins: [],
}
